
// Auto-generated by generateFileList.js
const files = {
  ".": [
    "index.html"
  ],
  "WEEK1": [
    "index.html"
  ],
  "WEEK2": [
    "index.html",
    "responsiveHW.html"
  ],
  "WEEK3": [
    "index.html",
    "jspuzzle.html"
  ],
  "WEEK4": [
    "index.html"
  ],
  "WEEK5": [
    "index.html",
    "response.html"
  ]
};
