// generateFileList.js
// Run this with: node generateFileList.js

const fs = require("fs");
const path = require("path");

const repoRoot = __dirname; // folder where this script lives
const outputFile = path.join(repoRoot, "fileList.js");

// recursive search for .html files
function getHtmlFiles(dir, base = "") {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let results = {};

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const folderPath = path.join(dir, entry.name);
      const subResults = getHtmlFiles(folderPath, path.join(base, entry.name));
      if (Object.keys(subResults).length > 0) {
        results[entry.name] = subResults[entry.name] || [];
        // merge in nested results
        for (const [k, v] of Object.entries(subResults)) {
          results[k] = v;
        }
      }
    } else if (entry.isFile() && entry.name.endsWith(".html")) {
      const folder = base || ".";
      if (!results[folder]) results[folder] = [];
      results[folder].push(entry.name);
    }
  }

  return results;
}

const files = getHtmlFiles(repoRoot);

// write it out as a JS file you can import in index.html
const content = `
// Auto-generated by generateFileList.js
const files = ${JSON.stringify(files, null, 2)};
`;

fs.writeFileSync(outputFile, content);
console.log(`✅ File list written to ${outputFile}`);
